version: "3"
vars:
  TEMPL_PROXYBIND: '{{.TEMPL_PROXYBIND | default "127.0.0.1"}}'
  TEMPL_PROXYPORT: '{{.TEMPL_PROXYPORT | default "7331"}}'
  TEMPL_PROXY: '{{.TEMPL_PROXY | default "http://127.0.0.1:9000"}}'
tasks:
  # Development Tools
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --cmd="go run ./cmd/server/main.go" --proxybind="{{.TEMPL_PROXYBIND}}" --proxyport="{{.TEMPL_PROXYPORT}}" --proxy="{{.TEMPL_PROXY}}" --open-browser=false
  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --clean
  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch
  # Start development server
  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-clean
    cmds:
      - echo "Starting app..."
      - task --parallel tailwind-watch templ

  # Testing
  test:
    desc: Run tests (SQLite only)
    cmds:
      - go test ./internal/... -v -count=1

  test:integration:
    desc: Run tests against both SQLite and PostgreSQL
    cmds:
      - docker run --name budgit-test-pg -d -p 5433:5432 -e POSTGRES_USER=budgit_test -e POSTGRES_PASSWORD=testpass -e POSTGRES_DB=budgit_test postgres:16-alpine
      - defer: docker rm -f budgit-test-pg
      - cmd: sleep 3
      - cmd: BUDGIT_TEST_POSTGRES_URL="postgres://budgit_test:testpass@localhost:5433/budgit_test?sslmode=disable" go test ./internal/... -v -count=1

  # Production build
  build:
    desc: Build production binary
    vars:
      VERSION:
        sh: git describe --tags --always
    cmds:
      - tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --minify
      - go tool templ generate
      - mkdir -p ./dist
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version={{.VERSION}}" -o ./dist/budgit ./cmd/server/main.go
